[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.2"

# Description
category = "isaaclab"
readme  = "README.md"

title = "Isaac Drone Racer"
author = "Ai Robotics @ Berkeley"
maintainer = "Ai Robotics @ Berkeley"
description="Isaac Drone Racer framework for RL based drone racing with IsaacLab"
repository = "https://github.com/airobotics-ucberkeley/isaac_drone_racer_public"
keywords = ["isaaclab", "drone", "rl"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_mimic" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "isaac_drone_racer"

[isaaclab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
